#!/usr/bin/env bash

if [ "$1" == "" ]; then
    echo "Usage: $0 <stream name>"
    exit 42
fi

# were here at a scheduled time to take a photo
# this means:
# 1 - do it quick
# 2 - safely with a lock

source ~/daylapse/secrets.sh

hass_sensor() {
    sensor_read=$(mktemp /dev/shm/read.XXXXXX)
    curl -s -X GET -H "Authorization: Bearer $hass_llac" \
       -H "Content-Type: application/json" \
       https://hass.vanstaveren.us/api/states/sensor.$1 \
       > $sensor_read
    if [ $? -ne 0 ]; then
	return -1
    fi
    value=$(cat $sensor_read | jq -r .state)
    echo "Value: $value" > /dev/stderr
    rm -f $sensor_read
    #return $value
    echo $value
}

out=$(mktemp /dev/shm/out.XXXXXX)

lock=/dev/shm/camera-lock
touch $lock
flock --verbose -w 30 $lock raspistill --awb sun --encoding png -o $out

stream=$1

# cloudcover=$(curl $hass# fixme
cloudcover=$(hass_sensor openweathermap_home_forecast_cloud_coverage)
solarrad=$(hass_sensor pws_solar_radiation_w_m2)
# TODO: log sun and moon alt/azi


stamp=$(date -u +%Y%m%d-%H%M%S)
dir=~/daylapse/streams/$stream
mkdir -p $dir
file=$dir/$stamp.png
cp $out $file
rm -f $dir/latest.{png,jpeg}
pushd $dir
ln -s $stamp.png latest.png
time convert -resize 1280x1024 -quality 50 latest.png latest.jpeg
popd

time exiftool -config ~/daylapse/exiftool.conf -SolarRadiation=$solarrad -CloudCover=$cloudcover $file

rm -f $out
# notify done
